version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
